[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
omit = [
    '*/test*',
    '*/.venv/*',
]

[tool.pytest.ini_options]
addopts = '--cov=wallsy --cov-fail-under=10'